"""empty message

Revision ID: 2a8236d071fa
Revises: 
Create Date: 2023-06-20 20:24:37.253515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8236d071fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('MAN', 'WOMAN', 'OTHER', name='genderenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.Enum('HOSPITAL_ROOM_6', 'HOSPITAL_ROOM_7', 'DUTY', name='locationenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('SURGEON', 'ENT', 'OPHTHALMOLOGIST', name='specialtyenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('AWAITING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'MISSED', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=35), nullable=False),
    sa.Column('last_name', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'worker_id')
    )
    # ENUM
    op.execute("INSERT INTO gender (id, name) VALUES (1, 'MAN')")
    op.execute("INSERT INTO gender (id, name) VALUES (2, 'WOMAN')")
    op.execute("INSERT INTO gender (id, name) VALUES (3, 'OTHER')")
    op.execute("INSERT INTO specialty (id, name) VALUES (1, 'SURGEON')")
    op.execute("INSERT INTO specialty (id, name) VALUES (2, 'ENT')")
    op.execute("INSERT INTO specialty (id, name) VALUES (3, 'OPHTHALMOLOGIST')")
    op.execute("INSERT INTO status (id, name) VALUES (1, 'AWAITING')")
    op.execute("INSERT INTO status (id, name) VALUES (2, 'CONFIRMED')")
    op.execute("INSERT INTO status (id, name) VALUES (3, 'CANCELLED')")
    op.execute("INSERT INTO status (id, name) VALUES (4, 'COMPLETED')")
    op.execute("INSERT INTO status (id, name) VALUES (5, 'MISSED')")
    op.execute("INSERT INTO location (id, place) VALUES (1, 'HOSPITAL_ROOM_6')")
    op.execute("INSERT INTO location (id, place) VALUES (2, 'HOSPITAL_ROOM_7')")
    op.execute("INSERT INTO location (id, place) VALUES (3, 'DUTY')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('appointment')
    op.drop_table('worker')
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('specialty')
    op.drop_table('location')
    op.drop_table('gender')
    # ### end Alembic commands ###
