language: python

python:
 - "3.9"

services:
  - postgresql

before_script:
  - psql -c 'create database meduzzen;' -U postgres

install:
 - pip install -r requirements.txt

script:
 - python -m pylint app
 - flask db upgrade
