version: '3.8'

services:
  web:
    build: .
    command: bash -c "flask db upgrade && python create_users.py && gunicorn -b 0.0.0.0:5000 main:app"
    volumes:
      - .:/meduzzen
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
      - worker

  worker:
    build: .
    command: ["celery", "-A", "app.config.celery_instance.celery", "worker", "--loglevel=info"]
    volumes:
      - .:/meduzzen
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:6.2.1-alpine

  rabbitmq:
    image: rabbitmq:3.8-management-alpine

volumes:
  postgres_data: